### PR TITLE
Add Type I and Type II tests, and improve readability

### PR DESCRIPTION
**Pull request by adamblake**
This commit adds a bunch of new functionality:
- can compute different SS types, e.g. `supernova(fit, type = 2)`
- improve the readability and clarity of `supernova()` and the extraction functions (`b0`, `fVal`, etc.). It should be much easier for someone to read through the function definitions and see what and how things are being calculated
- `generate_models(model, type)` to show what models are being compared when fitting different types of SS
- documentation for `generate_models()` gives a fairly detailed explanation of what models are being compared
- extract SSE and SSM just like with PRE, fVal, etc.
- consolidates some of the documentation into semantically similar pages

### CODE REVIEW

**Comment by jimstigler** [comment]
Adam: Ji is here on Monday mornings... do you think you could come by and give us a demo and walkthrough of the new features, maybe this coming Monday?

**Comment by adamblake** [comment]
A few changes were proposed in our meeting:

1. The comparison models created by `generate_models()` should be organized by term, not by augmented/compact
2. Terminology should be *complex* = augmented and *simple* = compact
3. supernova objects should have three components:
    a. `tbl`: the values from the supernova table
    b. `fit`: the model fit that was passed into supernova
    c. `models`: the models that were compared to get the values in `tbl`

### Example usage and print
```r
height_sex <- supernova(lm(Thumb ~ Height * Sex, data = Fingers), type = 1)

height_sex$models
#> Comparison Models for Type I SS
#> Model: Thumb ~ Height * Sex
#> 
#> Full model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#>
#> Height
#>   complex: Thumb ~ Height
#>    simple: Thumb ~ NULL
#> 
#> Sex
#>   complex: Thumb ~ Height + Sex
#>    simple: Thumb ~ Height
#>
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex

height_sex.sex <- height_sex$models$Sex

height_sex.sex
#> complex: Thumb ~ Height + Sex
#>  simple: Thumb ~ Height

height_sex.sex$complex
#> Thumb ~ Height + Sex

height_sex.sex$simple
#> Thumb ~ Height

anova(height_sex.sex$simple, height_sex.sex$complex)
#> Analysis of Variance Table
#> 
#> Model 1: Thumb ~ Height
#> Model 2: Thumb ~ Height + Sex
#>   Res.Df   RSS Df Sum of Sq    F Pr(>F)
#> 1    155 10063                         
#> 2    154  9916  1       148 2.29   0.13

# Note that Sum of Sq above corresponds to SS for Sex below

#> Analysis of Variance Table (Type I SS)
#>  Model: Thumb ~ Height * Sex
#>  
#>                                      SS  df       MS      F    PRE     p
#>  ---------- ----------------- --------- --- -------- ------ ------ -----
#>       Model (error reduced) |  1964.753   3  654.918 10.106 0.1654 .0000
#>      Height                 |  1816.862   1 1816.862 28.035 0.1549 .0000
#>         Sex                 |   147.662   1  147.662  2.278 0.0147 .1332
#>  Height:Sex                 |     0.229   1    0.229  0.004 0.0000 .9527
#>       Error (from model)    |  9915.458 153   64.807                    
#>  ---------- ----------------- --------- --- -------- ------ ------ -----
#>       Total (empty model)   | 11880.211 156   76.155
```

**Comment by jiyunson** [comment]
@adamblake I like it much better. Could you also make a height_sex$models output these for type II and III?

**Comment by adamblake** [comment]
### Type 2
```r
height_sex <- supernova(lm(Thumb ~ Height * Sex, data = Fingers), type = 2)

height_sex$models
#> Comparison Models for Type II SS
#> Model: Thumb ~ Height * Sex
#> 
#> Full model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#>
#> Height
#>   complex: Thumb ~ Height + Sex
#>    simple: Thumb ~          Sex
#> 
#> Sex
#>   complex: Thumb ~ Height + Sex
#>    simple: Thumb ~ Height
#>
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex

height_sex.height <- height_sex$models$Height

height_sex.height
#> complex: Thumb ~ Height + Sex
#>  simple: Thumb ~          Sex

height_sex.height$complex
#> Thumb ~ Height + Sex

height_sex.height$simple
#> Thumb ~ Sex

anova(height_sex.height$simple, height_sex.height$complex)
#> Analysis of Variance Table
#> 
#> Model 1: Thumb ~ Height
#> Model 2: Thumb ~ Height + Sex
#>   Res.Df   RSS Df Sum of Sq    F Pr(>F)
#> 1    155 10546                         
#> 2    154  9916  1       630 9.79 0.0021

# Note that Sum of Sq above corresponds to SS for Sex below

#> Analysis of Variance Table (Type II SS)
#> Model: Thumb ~ Height * Sex
#> 
#>                                     SS  df      MS      F    PRE     p
#> ---------- ----------------- --------- --- ------- ------ ------ -----
#>      Model (error reduced) |  1964.753   3 654.918 10.106 0.1654 .0000
#>     Height                 |   630.321   1 630.321  9.726 0.0598 .0022
#>        Sex                 |   147.662   1 147.662  2.278 0.0147 .1332
#> Height:Sex                 |     0.229   1   0.229  0.004 0.0000 .9527
#>      Error (from model)    |  9915.458 153  64.807                    
#> ---------- ----------------- --------- --- ------- ------ ------ -----
#>      Total (empty model)   | 11880.211 156  76.155  
```

### Type 3
```r
height_sex <- supernova(lm(Thumb ~ Height * Sex, data = Fingers))

height_sex$models
#> Comparison Models for Type III SS
#> Model: Thumb ~ Height * Sex
#>
#> NOTE: The individual models for each term cannot be compared using anova(): use drop1() instead.
#>       This only applies to Type III SS. See ?generate_models for more details.
#> 
#> Full model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#>
#> Height
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~          Sex + Height:Sex
#> 
#> Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height       + Height:Sex
#>
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex

height_sex.height <- height_sex$models$Height

height_sex.height
#> complex: Thumb ~ Height + Sex + Height:Sex
#>  simple: Thumb ~          Sex + Height:Sex

height_sex.height$complex
#> Thumb ~ Height + Sex + Height:Sex

height_sex.height$simple
#> Thumb ~ Sex + Height:Sex

anova(height_sex.height$simple, height_sex.height$complex)
#> Analysis of Variance Table
#> 
#> Model 1: Thumb ~ Sex + Height:Sex
#> Model 2: Thumb ~ Height + Sex + Height:Sex
#>   Res.Df   RSS Df Sum of Sq    F Pr(>F)
#> 1    153  9915                         
#> 2    153  9915  0 -9.09e-12 

# Note that even though the header above implies that the correct two models
# were compared, the Df and Sum of Sq are 0 because anova() will implicitly 
# add any "missing" lower-order terms when their interaction is present.

#> Analysis of Variance Table (Type III SS)
#> Model: Thumb ~ Height * Sex
#> 
#>                                     SS  df      MS      F    PRE     p
#> ---------- ----------------- --------- --- ------- ------ ------ -----
#>      Model (error reduced) |  1964.753   3 654.918 10.106 0.1654 .0000
#>     Height                 |   436.437   1 436.437  6.734 0.0422 .0104
#>        Sex                 |     1.283   1   1.283  0.020 0.0001 .8883
#> Height:Sex                 |     0.229   1   0.229  0.004 0.0000 .9527
#>      Error (from model)    |  9915.458 153  64.807                    
#> ---------- ----------------- --------- --- ------- ------ ------ -----
#>      Total (empty model)   | 11880.211 156  76.155

**Comment by adamblake** [comment]
Here are the type 2 and 3 mock-ups, @jiyunson (above)

**Comment by adamblake** [comment]
Okay --- here is actual output from this build of `supernova()`. I think I covered everything we talked about in our meeting. What do you think?

I also consolidated PR #20 here (the one where I re-exported all of the other functions we use in the course from our package) because I wanted to make use of some of those packages. I closed that PR, but you can take a look if you want to see the list of functions I pulled in.

```r
generate_models(lm(Thumb ~ Height * Sex, data = Fingers), type = 1)

#> Comparison Models for Type I SS
#> Model: Thumb ~ Height * Sex
#> 
#> Full Model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#> Height
#>   complex: Thumb ~ Height
#>    simple: Thumb ~ 1
#> Sex
#>   complex: Thumb ~ Height + Sex
#>    simple: Thumb ~ Height
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex

generate_models(lm(Thumb ~ Height * Sex, data = Fingers), type = 2)

#> Comparison Models for Type II SS
#> Model: Thumb ~ Height * Sex
#> 
#> Full Model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#> Height
#>   complex: Thumb ~ Height + Sex
#>    simple: Thumb ~          Sex
#> Sex
#>   complex: Thumb ~ Height + Sex
#>    simple: Thumb ~ Height
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex

generate_models(lm(Thumb ~ Height * Sex, data = Fingers), type = 3)

#> Comparison Models for Type III SS
#> Model: Thumb ~ Height * Sex
#> 
#> Full Model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#> Height
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~          Sex + Height:Sex
#> Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height +       Height:Sex
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex
#> Warning message:
#> In generate_models(lm(Thumb ~ Height * Sex, data = Fingers), type = 3) :
#>   The Type III models generated cannot be compared using anova().
#>   For model comparisons with Type III, use drop1() instead.
#>   Type ?generate_models() for more details.

sup_mod <- supernova(lm(Thumb ~ Height * Sex, Fingers))
sup_mod$models

#> Comparison Models for Type III SS
#> Model: Thumb ~ Height * Sex
#> 
#> Full Model
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ NULL
#> Height
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~          Sex + Height:Sex
#> Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height +       Height:Sex
#> Height:Sex
#>   complex: Thumb ~ Height + Sex + Height:Sex
#>    simple: Thumb ~ Height + Sex
```

**Comment by adamblake** [comment]
This needs to be re-evaluated and broken into separate pull requests:
1. Type I / Type II
2. Re-exports

**Pull request closed without merging**
