### PR TITLE
Convert Servers data to Tables

### PR DESCRIPTION
**Pull request by adamblake**
Add a data frame identical to Servers and change the name to Tables. This is a more appropriate name for the dataset because each row describes what happened at a table in the restaurant.

Update variable names and documentation to "table" as well.

Add deprecation notice to Servers documentation

### CODE REVIEW

**Comment by adamblake** [comment]
I merged in your updates to the TipDescription and fixed up the versioning, dates, etc. in the package DESCRIPTION. 

The build passes all R CMD CHECK flags, so it looks good to go!

**Comment by jimstigler** [comment]
I'm merging this into master. Please test ASAP to make sure it works as expected. Now I am waiting for Ji's changes to the text, after which I'll do the release of version 1.6.

**Comment by adamblake** [comment]
The datasets are fine but the documentation is off. I will figure out what is going on and fix it

**Comment by adamblake** [comment]
Nevermind that was a local issue because I was working on a different version simultaneously. I re-downloaded and everything looks great

**Pull request merged**
