### PR TITLE
Add pairwise comparisons functions

### PR DESCRIPTION
**Pull request by adamblake**
This PR would add four pairwise comparisons functions:

- `pairwise_comparisons()`
- `pairwise_t()`
- `pairwise_bonferroni()`
- `pairwise_tukey()`

Each function produces output that has customized printing, supports most (if not all) normal data frame actions, and a plotting function.

## Installing this PR

If you would like to test this PR for yourself, run the following code:

```r
remotes::install_github("UCLATALL/supernova", "feature/post-hoc")
```

When you are done testing and want to go back to the normal build, run

```r
remove.packages("supernova")
install.packages("supernova")
```

## `pairwise_comparisons()`

This function is a wrapper around the other functions, so here I will just show how it dispatches to those functions.

```r
library(supernova)
fit <- lm(Thumb ~ RaceEthnic, data = Fingers)

# t-test with no adjustments
pairwise_comparisons(fit, correction = "none")

# t-test with Bonferroni adjustment
pairwise_comparisons(fit, correction = "Bonferroni")

# Tukey's HSD
pairwise_comparisons(fit, correction = "Tukey")

# default is Tukey
pairwise_comparisons(fit)
```

## `pairwise_t()`

This function computes pairwise t-tests that describe all categorical terms in the model. Each family of tests (e.g. all the tests for one term) is reported in it's own table with the calculated family-wise error-rate for those tests. The resulting object has a class of `pairwise_comparisons` and can be plotted as demonstrated below.

### Setup

```r
library(supernova)
fit <- lm(Thumb ~ RaceEthnic, data = Fingers)
```

### Main output

```r
pairwise_t(fit)
```

```
── Pairwise t-tests ──────────────────────────────────────────

Model: Thumb ~ RaceEthnic

── RaceEthnic 
10 comparisons of 5 levels
Family-wise error-rate: 0.401

   group_1          group_2            diff pooled_se statistic  lower  upper p_val
   <chr>            <chr>             <dbl>     <dbl>     <dbl>  <dbl>  <dbl> <dbl>
 1 African American White             2.985     2.861     1.043 -1.749  7.720 .2984
 2 Asian            White            -0.964     1.672    -0.577 -3.730  1.802 .5649
 3 Latino           White            -1.796     2.028    -0.886 -5.152  1.560 .3771
 4 Other            White             5.929     2.762     2.147  1.359 10.500 .0334
 5 Asian            African American -3.949     2.833    -1.394 -8.638  0.739 .1654
 6 Latino           African American -4.782     3.057    -1.564 -9.841  0.277 .1199
 7 Other            African American  2.944     3.586     0.821 -2.991  8.879 .4129
 8 Latino           Asian            -0.832     1.988    -0.419 -4.123  2.459 .6762
 9 Other            Asian             6.894     2.733     2.523  2.371 11.416 .0127
10 Other            Latino            7.726     2.964     2.606  2.820 12.631 .0101
```

### Plot

```r
comparisons <- pairwise_t(fit)
plot(comparisons)
```

image

**Note:** The confidence percentage is based on the family-wise error rate. If you did a test of a term with only one comparisons, it would be a 95% confidence interval.

### Other arguments

To make this function comprehensive, there are three other arguments:

- `term`: select the term you want to limit the comparisons to. This is useful in models with interactions, e.g. in the model `Thumb ~ Sex * RaceEthnic` you may only  want to break down `Sex:RaceEthnic` and not `RaceEthnic` and `Sex` on their own.
- `alpha`: for this function, this term controls the confidence level per test. Essentially the family-wise error-rate will be `1 - (1 - alpha)^m` where `m` is the number of tests.
- `correction`: because the Bonferroni adjustment can be applied to t-tests, `pairwise_t(correction = "Bonferroni"` is equivalent to `pairwise_bonferroni()`

## `pairwise_bonferroni()`

```r
comparisons <- pairwise_bonferroni(fit)
comparisons
plot(comparisons)
```

```
── Pairwise t-tests with Bonferroni correction ────────────────────────────────

Model: Thumb ~ RaceEthnic

── RaceEthnic 
10 comparisons of 5 levels
Family-wise error-rate: 0.049

   group_1          group_2            diff pooled_se statistic   lower  upper  p_adj
   <chr>            <chr>             <dbl>     <dbl>     <dbl>   <dbl>  <dbl>  <dbl>
 1 African American White             2.985     2.861     1.043  -4.478 10.448 1.0000
 2 Asian            White            -0.964     1.672    -0.577  -5.324  3.396 1.0000
 3 Latino           White            -1.796     2.028    -0.886  -7.086  3.493 1.0000
 4 Other            White             5.929     2.762     2.147  -1.274 13.133  .3337
 5 Asian            African American -3.949     2.833    -1.394 -11.340  3.441 1.0000
 6 Latino           African American -4.782     3.057    -1.564 -12.756  3.193 1.0000
 7 Other            African American  2.944     3.586     0.821  -6.410 12.298 1.0000
 8 Latino           Asian            -0.832     1.988    -0.419  -6.019  4.355 1.0000
 9 Other            Asian             6.894     2.733     2.523  -0.235 14.022  .1268
10 Other            Latino            7.726     2.964     2.606  -0.006 15.458  .1006
```

image

### `pairwise_tukey()`

```r
comparisons <- pairwise_tukey(fit)
comparisons
plot(comparisons)
```

```
── Tukey's Honestly Significant Differences ────────────────────────────────

Model: Thumb ~ RaceEthnic

── RaceEthnic 
10 comparisons of 5 levels
Family-wise error-rate: 0.05

   group_1          group_2            diff pooled_se statistic   lower  upper p_adj
   <chr>            <chr>             <dbl>     <dbl>     <dbl>   <dbl>  <dbl> <dbl>
 1 African American White             2.985     2.023     1.476  -4.913 10.884 .8347
 2 Asian            White            -0.964     1.182    -0.816  -5.579  3.651 .9783
 3 Latino           White            -1.796     1.434    -1.253  -7.394  3.802 .9018
 4 Other            White             5.929     1.953     3.037  -1.695 13.554 .2058
 5 Asian            African American -3.949     2.003    -1.971 -11.771  3.872 .6325
 6 Latino           African American -4.782     2.162    -2.212 -13.221  3.658 .5227
 7 Other            African American  2.944     2.536     1.161  -6.956 12.844 .9238
 8 Latino           Asian            -0.832     1.406    -0.592  -6.322  4.657 .9935
 9 Other            Asian             6.894     1.932     3.567  -0.651 14.438 .0910
10 Other            Latino            7.726     2.096     3.686  -0.458 15.909 .0742
```

image

## A model with multiple terms

When a model has multiple terms, the family-wise error-rate is handled per term (this is how it works with `TukeyHSD` as well). Generally, when doing research you will want to choose the term you are looking at, but if you do not, these functions will produce output for all valid terms.

```r
comparisons <- pairwise_tukey(lm(Thumb ~ RaceEthnic * Sex, data = Fingers))
comparisons
plot(comparisons)
```

```
── Tukey's Honestly Significant Differences ─────────────────────────────────

Model: Thumb ~ RaceEthnic * Sex

── RaceEthnic 
10 comparisons of 5 levels
Family-wise error-rate: 0.05

   group_1          group_2            diff pooled_se statistic   lower  upper p_adj
   <chr>            <chr>             <dbl>     <dbl>     <dbl>   <dbl>  <dbl> <dbl>
 1 African American White             2.985     1.907     1.566  -4.463 10.434 .8026
 2 Asian            White            -0.964     1.114    -0.865  -5.316  3.387 .9730
 3 Latino           White            -1.796     1.352    -1.329  -7.075  3.483 .8809
 4 Other            White             5.929     1.841     3.221  -1.260 13.119 .1580
 5 Asian            African American -3.949     1.888    -2.091 -11.325  3.426 .5778
 6 Latino           African American -4.782     2.037    -2.347 -12.740  3.177 .4623
 7 Other            African American  2.944     2.390     1.232  -6.392 12.280 .9071
 8 Latino           Asian            -0.832     1.325    -0.628  -6.009  4.344 .9919
 9 Other            Asian             6.894     1.821     3.785  -0.221 14.008 .0624
10 Other            Latino            7.726     1.976     3.911   0.009 15.442 .0496

── Sex 
1 comparison of 2 levels
Family-wise error-rate: 0.05

  group_1 group_2  diff pooled_se statistic lower upper p_adj
  <chr>   <chr>   <dbl>     <dbl>     <dbl> <dbl> <dbl> <dbl>
1 male    female  6.120     1.011     6.055 3.295 8.944 .0000

── RaceEthnic:Sex 
45 comparisons of 10 levels
Family-wise error-rate: 0.05

   group_1                 group_2                   diff pooled_se statistic   lower  upper  p_adj
   <chr>                   <chr>                    <dbl>     <dbl>     <dbl>   <dbl>  <dbl>  <dbl>
 1 African American:female White:female             7.122     2.377     2.997  -3.677 17.920  .5173
 2 Asian:female            White:female             0.519     1.328     0.391  -5.516  6.554 1.0000
 3 Latino:female           White:female            -0.498     1.567    -0.318  -7.616  6.621 1.0000
 4 Other:female            White:female             7.764     2.250     3.450  -2.460 17.987  .3104
 5 White:male              White:female             9.192     1.736     5.295   1.305 17.080  .0095
 6 African American:male   White:female             3.836     3.027     1.267  -9.916 17.588  .9964
 7 Asian:male              White:female             5.964     1.775     3.360  -2.100 14.028  .3478
 8 Latino:male             White:female             7.169     2.535     2.828  -4.351 18.690  .6008
 9 Other:male              White:female            11.086     3.027     3.663  -2.666 24.838  .2319
10 Asian:female            African American:female -6.603     2.342    -2.820 -17.243  4.037  .6047
11 Latino:female           African American:female -7.619     2.485    -3.066 -18.909  3.671  .4832
12 Other:female            African American:female  0.642     2.963     0.217 -12.823 14.107 1.0000
13 White:male              African American:female  2.071     2.595     0.798  -9.719 13.860  .9999
14 African American:male   African American:female -3.286     3.589    -0.916 -19.593 13.021  .9997
15 Asian:male              African American:female -1.158     2.621    -0.442 -13.067 10.751 1.0000
16 Latino:male             African American:female  0.048     3.186     0.015 -14.427 14.522 1.0000
17 Other:male              African American:female  3.964     3.589     1.105 -12.343 20.271  .9988
18 Latino:female           Asian:female            -1.017     1.513    -0.672  -7.892  5.859 1.0000
19 Other:female            Asian:female             7.245     2.213     3.273  -2.811 17.300  .3860
20 White:male              Asian:female             8.673     1.688     5.139   1.004 16.342  .0137
21 African American:male   Asian:female             3.317     2.999     1.106 -10.311 16.945  .9987
22 Asian:male              Asian:female             5.445     1.728     3.151  -2.406 13.296  .4424
23 Latino:male             Asian:female             6.650     2.503     2.657  -4.722 18.022  .6831
24 Other:male              Asian:female            10.567     2.999     3.523  -3.061 24.195  .2820
25 Other:female            Latino:female            8.261     2.364     3.495  -2.480 19.002  .2930
26 White:male              Latino:female            9.690     1.881     5.151   1.142 18.238  .0133
27 African American:male   Latino:female            4.334     3.112     1.392  -9.808 18.475  .9927
28 Asian:male              Latino:female            6.462     1.917     3.370  -2.250 15.173  .3436
29 Latino:male             Latino:female            7.667     2.637     2.907  -4.315 19.649  .5615
30 Other:male              Latino:female           11.584     3.112     3.722  -2.558 25.725  .2126
31 White:male              Other:female             1.429     2.479     0.576  -9.837 12.694 1.0000
32 African American:male   Other:female            -3.928     3.506    -1.120 -19.859 12.004  .9986
33 Asian:male              Other:female            -1.800     2.507    -0.718 -13.190  9.591 1.0000
34 Latino:male             Other:female            -0.594     3.092    -0.192 -14.645 13.457 1.0000
35 Other:male              Other:female             3.322     3.506     0.948 -12.609 19.254  .9996
36 African American:male   White:male              -5.356     3.201    -1.673 -19.900  9.188  .9739
37 Asian:male              White:male              -3.228     2.058    -1.569 -12.579  6.122  .9831
38 Latino:male             White:male              -2.023     2.741    -0.738 -14.478 10.432 1.0000
39 Other:male              White:male               1.894     3.201     0.592 -12.650 16.438 1.0000
40 Asian:male              African American:male    2.128     3.222     0.660 -12.512 16.768 1.0000
41 Latino:male             African American:male    3.333     3.696     0.902 -13.460 20.127  .9998
42 Other:male              African American:male    7.250     4.049     1.791 -11.147 25.647  .9595
43 Latino:male             Asian:male               1.205     2.766     0.436 -11.362 13.773 1.0000
44 Other:male              Asian:male               5.122     3.222     1.590  -9.518 19.762  .9815
45 Other:male              Latino:male              3.917     3.696     1.060 -12.877 20.710  .9991
```

image

image

image

### Selecting a term

To select a specific term, just provide it to the function like this:

```r
comparisons <- pairwise_tukey(lm(Thumb ~ RaceEthnic * Sex, data = Fingers), "Sex")
comparisons
plot(comparisons)
```

```
── Tukey's Honestly Significant Differences ──────────────────────────────────

Model: Thumb ~ RaceEthnic * Sex

── Sex 
1 comparison of 2 levels
Family-wise error-rate: 0.05

  group_1 group_2  diff pooled_se statistic lower upper p_adj
  <chr>   <chr>   <dbl>     <dbl>     <dbl> <dbl> <dbl> <dbl>
1 male    female  6.120     1.011     6.055 3.295 8.944 .0000
```

image

## Models with non-categorical variables

Because you can't perform a pairwise comparison on non-categorical data, these terms are dropped before computing the comparisons. This is similar to how base R's `TukeyHSD` is supposed to work.

```r
comparisons <- pairwise_tukey(lm(Thumb ~ Height * Sex, data = Fingers), "Sex")
comparisons
plot(comparisons)
```

```
── Tukey's Honestly Significant Differences ────────────────────────────────

Model: Thumb ~ Height * Sex
! 1 non-categorical variable dropped: Height

── Sex 
1 comparison of 2 levels
Family-wise error-rate: 0.05

  group_1 group_2  diff pooled_se statistic lower upper p_adj
  <chr>   <chr>   <dbl>     <dbl>     <dbl> <dbl> <dbl> <dbl>
1 male    female  6.447     1.005     6.417 3.640 9.254 .0000
```

image

### CODE REVIEW

**Comment by adamblake** [comment]
At @jimstigler's request, I am changing the `statistic` column in the output to be `t` for t-tests and `q` for Tukey tests

**Comment by adamblake** [comment]
At @jimstigler's request I have changed the x-axis label for uncorrected t-tests to show "95% uncorrected" instead of 1 - family-wise error-rate:

image

**Review by jiyunson — COMMENTED** [review]
Hey Adam,
Amazing! So cool. Jim also said you were looking at whether `pairwise_comparisons()` can be shortened to `pairwise()`.

In the plots:
- can we say CI rather than conf. int.?
- can we label the plots for the corrected pairwise CIs like: "95% CI with Tukey correction" and we don't need to say "mean difference" in front of those.

A general question about how posthoc corrections work: when you have the situation where you have a more complex model (Y~ X1 * X2) and you select a variable for the Tukey correction (e.g., X2), does the subsequent CIs adjust for the effect of X1? Jim and I assumed it did but wanted to run it by you.

**Comment by adamblake** [comment]
@jiyunson Thanks!

I liked your changes to the plot labels and added those in. For the uncorrected it will say "95% CI (per test; uncorrected)" and the others like you had: "95% CI with Tukey correction"

@jimstigler & @jiyunson I changed the function to `pairwise()`.  For the question about whether the CIs/differences are adjusted for other predictors: in short, no, but below are a few cases and what would happen, specifically.

- `Y ~ Quant. + Cat.`: the quantitative variable is dropped and the tests compare the overall effect of each category. Quantitative variables are always dropped, and a note is given in the output that they were dropped.
- `Y ~ Cat. + Cat.`: two sets of tests are produced (one for each categorical variable). Each set of tests compare on their respective variable's category regardless of the other (main effects).
- `Y ~ Cat. * Cat.`: three sets of tests are produced (the two from the previous example and the interaction between the variables). The first two sets of tests are the main effects, and the third is comprised of all the simple effects.

**Comment by jimstigler** [comment]
Adam, this looks good to go to me... I assume you will merge whenever you are ready.

**Pull request merged**
